name: lint test deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: lint
        run: npx eslint .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm ci
      - name: test project
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: Deploy
        run: echo "deploying..."